#pragma once

#include "apu_communication.h"
#include "apu_components.h"
#include "apu_controller.h"
#include "apu_defs.h"

void perform_manual_actions(
    Actions_manual* actm,
    Physical* phys,
    Messages* msgs,
    Data* data,
    Problem_notifications* ntfs,
    State state,
    ECU* c0,
    ECU* c1,
    Starter* start,
    Gas_generator* ggen,
    Rotor* rotor,
    Compressor* comp,
    Cooling_fan* fan,
    Generator* gen,
    Fuel_pump* pump,
    Pneumatic_system* psys);

void perform_actions(
    Actions* acts,
    Messages* msgs,
    Data* data,
    Actions_manual* actm,
    Physical* phys,
    State* state,
    ECU* c0,
    ECU* c1,
    Starter* start,
    PID* pid,
    Gas_generator* ggen,
    Rotor* rotor,
    Compressor* comp,
    Generator* gen,
    Fuel_pump* pump,
    Pneumatic_system* psys);